[package]
name = "weatherstation-api"
version = "0.1.0"
authors = ["Wesley Klop <wesley19097@gmail.com>"]
edition = "2018"
default-run = "server"

[dependencies]
actix-web = "^3.0"
chrono = { version = "0.4.19", features = ["serde"] }
diesel = { version = "^1.4.0", features = ["chrono", "mysql", "r2d2", "uuid"] }
dotenv = "0.15.0"
r2d2 = "0.8.9"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
uuid = { version = "^0.8", features = ["serde", "v4"] }
