version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - 'db-data:/var/lib/postgresql/data'
      - './docker/dev-initdb.d:/docker-entrypoint-initdb.d:ro'
    ports:
      - 5432:5432

volumes:
  db-data:
